Removed no-magic-numbers rule
ChromatixAU/eslint-config-chromatix pull request #9
Opened 2018-10-25 00:17 UTC by dylanvanes

2018-10-26 03:06 UTC, juz501 requested changes

2018-10-26 03:06 UTC, juz501 commented on index.js
> +    'no-magic-numbers':      null,
Looks like 0 was correct
```suggestion
    'no-magic-numbers':      0,
```

2018-10-26 03:40 UTC, jay-oswald approved these changes

2018-10-29 02:30 UTC, juz501 approved these changes

2018-10-29 22:30 UTC, merged